version: '3.7'

services:
  web:
    volumes:
      - storage-volume:/opt/project/storage
      - vendor-volume:/opt/project/vendor

  php:
    volumes:
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - storage-volume:/opt/project/storage
      - vendor-volume:/opt/project/vendor

  bg-sync-node-modules:
    container_name: nightowl-bg-sync-node-modules
    image: cweagans/bg-sync
    volumes:
      - node-modules-volume:/source
      - ./node_modules:/destination:delegated
    environment:
      - SYNC_MAX_INOTIFY_WATCHES=40000
      - SYNC_VERBOSE=1
    privileged: true

  bg-sync-storage:
    container_name: nightowl-bg-sync-storage
    image: cweagans/bg-sync
    volumes:
      - storage-volume:/source
      - ./storage:/destination:delegated
    environment:
      - SYNC_MAX_INOTIFY_WATCHES=40000
      - SYNC_VERBOSE=1
    privileged: true

  bg-sync-vendor:
    container_name: nightowl-bg-sync-vendor
    image: cweagans/bg-sync
    volumes:
      - vendor-volume:/source
      - ./vendor:/destination:delegated
    environment:
      - SYNC_MAX_INOTIFY_WATCHES=40000
      - SYNC_VERBOSE=1
    privileged: true

volumes:
  node-modules-volume:
  storage-volume:
  vendor-volume:
