version: '3.7'

services:
  web:
    env_file: .env
    image: panubo/sshd:1.2.0
    container_name: nightowl-ssh
    tty: true
    volumes:
      - .:/opt/project
      - ${DOCKER_RSA_FILE}:/tmp/.ssh/id_rsa
      - ${DOCKER_RSA_PUB_FILE}:/tmp/.ssh/id_rsa.pub
