name: Build images and deploy to production
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    name: Build images and push to registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create buildx context
        run: docker buildx create --use

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build app image
        run: >
          docker buildx build
          --platform=linux/amd64
          --build-arg BUILDKIT_INLINE_CACHE=1
          --cache-from ghcr.io/buzzingpixel/nightowl.fm-app
          --file docker/application/Dockerfile
          --tag ghcr.io/buzzingpixel/nightowl.fm-app
          --push
          .

      - name: Build schedule-runner image
        run: >
          docker buildx build
          --platform=linux/amd64
          --build-arg BUILDKIT_INLINE_CACHE=1
          --cache-from ghcr.io/buzzingpixel/nightowl.fm-app-schedule-runner
          --file docker/schedule-runner/Dockerfile
          --tag ghcr.io/buzzingpixel/nightowl.fm-app-schedule-runner
          --push
          .

      - name: Build db image
        run: >
          docker buildx build
          --platform=linux/amd64
          --build-arg BUILDKIT_INLINE_CACHE=1
          --cache-from ghcr.io/buzzingpixel/nightowl.fm-db
          --file docker/db/Dockerfile
          --tag ghcr.io/buzzingpixel/nightowl.fm-db
          --push
          .

      - name: Build utility image
        run: >
          docker buildx build
          --platform=linux/amd64
          --build-arg BUILDKIT_INLINE_CACHE=1
          --cache-from ghcr.io/buzzingpixel/nightowl.fm-utility
          --file docker/utility/Dockerfile
          --tag ghcr.io/buzzingpixel/nightowl.fm-utility
          --push
          .

  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, 'master')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy Files
        uses: appleboy/scp-action@master
        with:
          username: ${{ vars.PROD_DEPLOY_SSH_USER }}
          host: ${{ vars.PROD_DEPLOY_SSH_HOST }}
          key: ${{ secrets.PROD_DEPLOY_SSH_PRIVATE_KEY }}
          source: ".env, docker-compose.prod.yml"
          target: "/root/nightowl.fm"

      - name: Log in to production server pull images, and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ vars.PROD_DEPLOY_SSH_USER }}
          host: ${{ vars.PROD_DEPLOY_SSH_HOST }}
          key: ${{ secrets.PROD_DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            cd /root/nightowl.fm;

            # Log in to github docker registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin;

            # Pull Images
            docker pull ghcr.io/buzzingpixel/nightowl.fm-app;
            docker pull ghcr.io/buzzingpixel/nightowl.fm-app-schedule-runner;
            docker pull ghcr.io/buzzingpixel/nightowl.fm-db;
            docker pull ghcr.io/buzzingpixel/nightowl.fm-utility;

            # Docker can be weird about .env, make sure local is concat into .env
            cat /root/nightowl.fm/.env.local >> /root/nightowl.fm/.env;

            # Deploy new images
            docker stack deploy \
              --compose-file docker-compose.prod.yml \
              --prune \
              --with-registry-auth \
              --resolve-image always \
              nightowl;
